easy_admin:
    site_name: 'MY CV APP'
    entities:
#        # List the entity class name you want to manage
        Cv:
            class: App\Entity\Cv
        Experience:
            class: App\Entity\Experience

        Formation:
            class: App\Entity\Formation

        Skill:
            class: App\Entity\Skill

#        User:
#            class: App\Entity\User
#            form:
#                fields:
#                    - email
#                    # if administrators are allowed to edit users' passwords and roles, add this:
#                    - { property: 'Password', type: 'text', type_options: { required: false } }
#                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


        DefaultConfig:
            class: App\Entity\DefaultConfig

