easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Cv
        - App\Entity\Experience
        - App\Entity\Formation
        - App\Entity\Skill
        - App\Entity\User
        - App\Entity\DefaultConfig

