vich_uploader:
    db_driver: orm

    mappings:
        people_images:
            uri_prefix:         '%app.path.people_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.people_images%'
